
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: "verified_email"
              Priority: 1
            - Name: "verified_phone_number"
              Priority: 2
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          UnusedAccountValidityDays: 1
        DeletionProtection: "ACTIVE"
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: true
        EnabledMfas: 
          - "SOFTWARE_TOKEN_MFA"
        MfaConfiguration:
          "OPTIONAL"
        UserPoolName: "OrgFin-users"