
  Resources:
    InsomniaClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref UserPool
        ClientName: Insomnia
    Domain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: api-transacoes
        UserPoolId: !Ref UserPool
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: "verified_email"
              Priority: 1
            - Name: "verified_phone_number"
              Priority: 2
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          UnusedAccountValidityDays: 1
        DeletionProtection: "ACTIVE"
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: true
        EnabledMfas: 
          - "SOFTWARE_TOKEN_MFA"
        MfaConfiguration:
          "OPTIONAL"
        UserPoolName: "OrgFin-users"